### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by AbnerTeng** [yuiint/Housing-Reinforcement-Prediction#1]
1. We usually won't write too much in `main.py`. Instead, create more python scripts like `utils.py`, `data.py`, `model.py` for a tidy look.
2. Is `code.ipynb` necessary?
3.  Prevent from leaving `# your comment` in your code after refactoring, it's not beautiful.
4.  Use `enumerate()` instead of `range(len())`
5. Variable name `X` usually stands for CONSTANT, but in your code,  `X` seems to be features not CONSTANT
6. Use fstring `f"Hi: {name}"` instead of `.format()`

Remains looks good to me,  I like the aware of CONSTANT and the perfect data type annotation

**Comment by AbnerTeng** [comment]
@yuiint Plz see the issue

**Comment by AbnerTeng** [comment]
Quite good refactor, btw, I like the way you store all the scenarios, that's neat!

**Comment by yuiint** [comment]
@AbnerTeng  \✨Many thanks✨/
